# NPTEL R Programming – Week 10
## Complete Python / Google Colab Implementation

This notebook translates the practical examples and functions from the supplied Week 10 R Programming notes into Python.

### Topics covered
1. String substitution and replacement
   - R `sub()` → Python `re.sub(..., count=1)`
   - R `gsub()` → Python `re.sub()`
2. String searching
   - R `grep()` → Python regular-expression search
   - R `grepl()` → Python Boolean matching
3. Data frames
   - Creation
   - Column/type inspection
   - Summary
   - Row names
   - Subsetting
   - Splitting
4. Combining and merging data frames
   - R `cbind()` → `pandas.concat(..., axis=1)`
   - R `merge()` → `pandas.merge()`
   - R `rbind()` → `pandas.concat(..., axis=0)`

The notebook is designed to run directly in Google Colab.

## 1. Setup

In [2]:
import re
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

print("Python environment ready.")
print("pandas version:", pd.__version__)

Python environment ready.
pandas version: 2.2.3

# Part A – Strings: Display, Formatting, Substitution and Replacement

The notes introduce `sub()` for replacing the **first** occurrence of a substring and `gsub()` for replacing **all** occurrences. fileciteturn1file0L13-L21

## 2. `sub()` equivalent – replace the first occurrence

In [3]:
# R:
# y = "Number of participants: 25"
# sub("25", "30", y)

y = "Number of participants: 25"

# Python equivalent of R sub(): replace only the first match
result = re.sub("25", "30", y, count=1)

print(result)

Number of participants: 30

In [4]:
# Example from the notes
y = "Mr. Singh is the smart one. Mr. Singh is funny, too."

# Replace only the first occurrence
result_sub = re.sub("Mr\\. Singh", "Professor Jha", y, count=1)

print(result_sub)

Professor Jha is the smart one. Mr. Singh is funny, too.

## 3. `gsub()` equivalent – replace all occurrences

In [5]:
y = "Mr. Singh is the smart one. Mr. Singh is funny, too."

# Python equivalent of R gsub(): replace every matching occurrence
result_gsub = re.sub("Mr\\. Singh", "Professor Jha", y)

print(result_gsub)

Professor Jha is the smart one. Professor Jha is funny, too.

## 4. `sub()` vs `gsub()` comparison

- `sub()` changes only the first matching occurrence.
- `gsub()` performs a global replacement.

This follows the distinction given in the notes. fileciteturn1file0L15-L20

In [6]:
text = "Mr. Singh met Mr. Singh and then called Mr. Singh."

first_only = re.sub("Mr\\. Singh", "Professor Jha", text, count=1)
all_matches = re.sub("Mr\\. Singh", "Professor Jha", text)

print("Original:    ", text)
print("First only:  ", first_only)
print("All matches: ", all_matches)

Original:     Mr. Singh met Mr. Singh and then called Mr. Singh.
First only:   Professor Jha met Mr. Singh and then called Mr. Singh.
All matches:  Professor Jha met Professor Jha and then called Professor Jha.

## 5. Regular-expression searching – `grep()`

The notes explain that `grep()` searches a character vector for matches and returns the indices by default. With `value=TRUE`, it returns the matching elements instead. fileciteturn1file0L77-L86 fileciteturn1file0L98-L115

In [7]:
strings = [
    "R Course",
    "exercises",
    "include examples of R language"
]

pattern = "ex"

# Python equivalent of grep(pattern, x):
# Return 0-based indices first, then convert to R-style 1-based indices.
matching_indices_python = [
    i for i, value in enumerate(strings)
    if re.search(pattern, value) is not None
]

matching_indices_r_style = [i + 1 for i in matching_indices_python]

print("Python indices (0-based):", matching_indices_python)
print("R-style indices (1-based):", matching_indices_r_style)

# Equivalent of grep(..., value=TRUE)
matching_values = [
    value for value in strings
    if re.search(pattern, value) is not None
]

print("Matching values:", matching_values)

Python indices (0-based): [1, 2]
R-style indices (1-based): [2, 3]
Matching values: ['exercises', 'include examples of R language']

### 5.1 Case-sensitive and case-insensitive search

In [8]:
strings = [
    "R Course",
    "exercises",
    "include examples of r language",
    "in R software."
]

pattern = "R"

# R grep("R", str, ignore.case=FALSE, value=TRUE)
case_sensitive = [
    value for value in strings
    if re.search(pattern, value) is not None
]

# R grep("R", str, ignore.case=TRUE, value=TRUE)
case_insensitive = [
    value for value in strings
    if re.search(pattern, value, flags=re.IGNORECASE) is not None
]

print("Case-sensitive matches:")
print(case_sensitive)

print("\nCase-insensitive matches:")
print(case_insensitive)

Case-sensitive matches:
['R Course', 'in R software.']

Case-insensitive matches:
['R Course', 'exercises', 'include examples of r language', 'in R software.']

In [9]:
# Return indices, equivalent to value=FALSE
case_sensitive_indices = [
    i + 1 for i, value in enumerate(strings)
    if re.search("R", value) is not None
]

case_insensitive_indices = [
    i + 1 for i, value in enumerate(strings)
    if re.search("R", value, flags=re.IGNORECASE) is not None
]

print("Case-sensitive indices (R-style):", case_sensitive_indices)
print("Case-insensitive indices (R-style):", case_insensitive_indices)

Case-sensitive indices (R-style): [1, 4]
Case-insensitive indices (R-style): [1, 2, 3, 4]

### 5.2 Search the combined `x` and `y` example

In [10]:
x = "R course 24.07.2021"
y = "Number of participants: 25"

combined = [x, y]

print("Combined strings:")
print(combined)

# grep("our", c(x, y))
our_indices = [
    i + 1 for i, value in enumerate(combined)
    if re.search("our", value) is not None
]

# grep("Num", c(x, y))
num_indices = [
    i + 1 for i, value in enumerate(combined)
    if re.search("Num", value) is not None
]

print("Indices containing 'our':", our_indices)
print("Indices containing 'Num':", num_indices)

Combined strings:
['R course 24.07.2021', 'Number of participants: 25']
Indices containing 'our': [1]
Indices containing 'Num': [2]

## 6. `grepl()` equivalent

The notes describe `grepl()` as returning TRUE/FALSE values indicating whether a match is available. fileciteturn1file0L180-L186

In [11]:
strings = [
    "R Course",
    "exercises",
    "include examples of R language"
]

# Equivalent of grepl("R", str)
grepl_R = [
    re.search("R", value) is not None
    for value in strings
]

print("grepl('R', strings):")
print(grepl_R)

# Equivalent of grepl("ex", str)
grepl_ex = [
    re.search("ex", value) is not None
    for value in strings
]

print("\ngrepl('ex', strings):")
print(grepl_ex)

grepl('R', strings):
[True, False, True]

grepl('ex', strings):
[False, True, True]

# Part B – Data Frames

The notes explain that data frames combine equal-length variables, can contain numerical and categorical data, and are structured similarly to spreadsheets: columns are variables and rows are observations. fileciteturn1file0L212-L230

## 7. Creating a data frame

In [12]:
# Basic Python/pandas equivalent of R data.frame()

students = pd.DataFrame({
    "Name": ["Amit", "Neha", "Ravi", "Priya"],
    "Marks": [85, 92, 76, 88],
    "Gender": ["M", "F", "M", "F"]
})

students

    Name  Marks Gender
0   Amit     85      M
1   Neha     92      F
2   Ravi     76      M
3  Priya     88      F

## 8. The `painters` data frame

The notes use the `painters` data set from the MASS package. It contains four numerical variables—Composition, Drawing, Colour and Expression—and one factor variable, School. fileciteturn1file0L303-L318

For a Python notebook, the data below reproduces the complete `painters` values shown across the supplied notes.

In [13]:
painters = pd.DataFrame(
    {
        "Composition": [10,15,8,12,0,15,8,15,4,17,10,13,10,15,13,12,14,16,10,13,11,15,6,4,8,6,12,5,8,15,12,15,14,6,13,15,18,14,15,8,16,15,15,10,13,18,15,15,10],
        "Drawing": [8,16,13,16,15,16,17,16,12,18,13,15,15,14,14,15,15,14,10,12,15,15,8,6,9,8,9,6,14,14,15,10,14,6,13,17,10,13,10,10,16,15,10,8,14,13,12,10,17],
        "Colour": [16,4,16,9,8,4,4,7,10,12,8,8,6,7,10,5,6,12,6,9,0,12,17,14,18,15,14,16,17,16,18,16,18,16,15,9,10,10,10,10,8,16,8,14,17,17,13],
        "Expression": [3,14,7,8,0,14,8,6,4,18,8,8,6,10,9,8,10,6,2,6,6,13,0,0,4,4,6,0,5,4,6,3,6,0,12,17,4,5,4,8,16,15,15,4,6,17,6,13,15],
        "School": list("AAAAAAAAAABBBBBBCCCCCCDDDDDDDDDD EEEEEEEFFFFGGGGGGGHHHH".replace(" ", ""))
    },
    index=[
        "Da Udine","Da Vinci","Del Piombo","Del Sarto","Fr. Penni",
        "Guilio Romano","Michelangelo","Perino del Vaga","Perugino","Raphael",
        "F. Zucarro","Fr. Salviata","Parmigiano","Primaticcio","T. Zucarro","Volterra",
        "Barocci","Cortona","Josepin","L. Jordaens","Testa","Vanius",
        "Bassano","Bellini","Giorgione","Murillo","Palma Giovane","Palma Vecchio",
        "Pordenone","Tintoretto","Titian","Veronese",
        "Albani","Caravaggio","Corregio","Domenichino","Guercino","Lanfranco","The Carraci",
        "Durer","Holbein","Pourbus","Van Leyden",
        "Diepenbeck","J. Jordaens","Otho Venius","Rembrandt","Rubens","Teniers","Van Dyck",
        "Bourdon","Le Brun","Le Suer","Poussin"
    ]
)

# Display the data
painters

ValueError: Length of values (49) does not match length of index (54)

In [14]:
# Inspect the structure
print("Shape:", painters.shape)
print("\nColumn names:")
print(list(painters.columns))

print("\nData types:")
print(painters.dtypes)

print("\nFirst five rows:")
display(painters.head())

NameError: name 'painters' is not defined

## 9. Checking variable types

In [15]:
# R:
# is.numeric(painters$School) -> FALSE
# is.numeric(painters$Drawing) -> TRUE
# is.factor(painters$School) -> TRUE
# is.factor(painters$Drawing) -> FALSE

print("School is numeric:", pd.api.types.is_numeric_dtype(painters["School"]))
print("Drawing is numeric:", pd.api.types.is_numeric_dtype(painters["Drawing"]))

# pandas does not have R's factor type by default.
# Categorical dtype is the closest direct equivalent.
painters["School"] = painters["School"].astype("category")

print("School is categorical:", isinstance(painters["School"].dtype, pd.CategoricalDtype))
print("Drawing is categorical:", isinstance(painters["Drawing"].dtype, pd.CategoricalDtype))

NameError: name 'painters' is not defined

## 10. Row names / index

In [16]:
# R uses rownames(painters); pandas uses the DataFrame index.

print("Painter names / row identifiers:")
print(painters.index.tolist())

print("\nFirst five row identifiers:")
print(painters.index[:5].tolist())

Painter names / row identifiers:

NameError: name 'painters' is not defined

## 11. Summary of the data frame

In [17]:
# R summary(painters) equivalent
print(painters.describe(include="all"))

NameError: name 'painters' is not defined

## 12. Frequency summary of a categorical variable

The notes show `summary(painters$School)` returning frequencies for each school category. fileciteturn1file0L419-L425

In [18]:
school_frequency = painters["School"].value_counts().sort_index()

print(school_frequency)

NameError: name 'painters' is not defined

## 13. Summary of a numerical variable

In [19]:
# Equivalent of summary(painters$Composition)
print(painters["Composition"].describe())

NameError: name 'painters' is not defined

## 14. `attach()` concept

R's `attach()` allows variables in a data frame to be referenced directly without `painters$`. The notes demonstrate this behavior and then use `detach()` to restore the default setting. fileciteturn1file0L430-L459

Python/pandas does not use `attach()`/`detach()`. The normal equivalent is to reference columns through the DataFrame, or explicitly assign a column when convenient.

In [20]:
# Preferred pandas style
print("Composition mean:", painters["Composition"].mean())

# If desired, create a local variable:
Composition = painters["Composition"]
School = painters["School"]

print("Composition mean using a local variable:", Composition.mean())
print("School categories:", School.unique().tolist())

NameError: name 'painters' is not defined

## 15. Subsetting rows

In [21]:
# R:
# subset(painters, School == "F")

school_F = painters[painters["School"] == "F"]
school_F

NameError: name 'painters' is not defined

In [22]:
# Equivalent indexing style
school_F_2 = painters.loc[painters["School"] == "F", :]
school_F_2

NameError: name 'painters' is not defined

In [23]:
# R:
# subset(painters, Composition <= 6)

composition_le_6 = painters[painters["Composition"] <= 6]
composition_le_6

NameError: name 'painters' is not defined

## 16. Selecting/removing columns

In [24]:
# R:
# subset(painters, School=="F", select=c(-3,-5))
#
# This removes the 3rd column (Colour) and 5th column (School).

school_F_selected = painters.loc[
    painters["School"] == "F",
    ["Composition", "Drawing", "Expression"]
]

school_F_selected

NameError: name 'painters' is not defined

## 17. `split()` equivalent

The notes use `split(painters, painters$School)` to partition the data set by School. fileciteturn1file0L559-L563

In [25]:
# pandas equivalent of R split()
splitted = {
    school: group.copy()
    for school, group in painters.groupby("School", observed=True)
}

for school, group in splitted.items():
    print(f"--- School {school} ---")
    display(group)

NameError: name 'painters' is not defined

In [26]:
# In R, splitted$A is itself a data frame.
# In pandas, each dictionary value is a DataFrame.
print("Is splitted['A'] a DataFrame:", isinstance(splitted["A"], pd.DataFrame))

NameError: name 'splitted' is not defined

# Part C – Combining and Merging Data Frames

The notes identify three main techniques:
- `cbind()` – combine columns side-by-side
- `merge()` – join using a common column
- `rbind()` – stack rows vertically fileciteturn1file0L680-L684

## 18. Create `df1` and `df2`

In [27]:
df1 = pd.DataFrame({
    "state": ["UP", "MP", "AP", "JK"],
    "popnsize": [1000, 2000, 3000, 4000]
})

df2 = pd.DataFrame({
    "state": ["UP", "MP", "AP", "JK"],
    "samplesize": [100, 200, 300, 400],
    "surveycompleted": ["Yes", "No", "Yes", "No"]
})

print("df1:")
display(df1)

print("df2:")
display(df2)

df1:

  state  popnsize
0    UP      1000
1    MP      2000
2    AP      3000
3    JK      4000

df2:

  state  samplesize surveycompleted
0    UP         100             Yes
1    MP         200              No
2    AP         300             Yes
3    JK         400              No

## 19. `cbind()` equivalent

The notes show `cbind(df1, df2)` combining columns side-by-side. fileciteturn1file0L689-L697

In [28]:
# pandas equivalent of cbind()
cbind_result = pd.concat(
    [df1.reset_index(drop=True), df2.reset_index(drop=True)],
    axis=1
)

cbind_result

  state  popnsize state  samplesize surveycompleted
0    UP      1000    UP         100             Yes
1    MP      2000    MP         200              No
2    AP      3000    AP         300             Yes
3    JK      4000    JK         400              No

## 20. `merge()` equivalent

The notes merge the two data frames using the common `state` column. fileciteturn1file0L731-L740

In [29]:
# pandas equivalent of merge(df1, df2, by="state")
merge_result = pd.merge(df1, df2, on="state")

merge_result

  state  popnsize  samplesize surveycompleted
0    UP      1000         100             Yes
1    MP      2000         200              No
2    AP      3000         300             Yes
3    JK      4000         400              No

In [30]:
# Different merge types for practice
print("Inner merge:")
display(pd.merge(df1, df2, on="state", how="inner"))

print("Left merge:")
display(pd.merge(df1, df2, on="state", how="left"))

print("Right merge:")
display(pd.merge(df1, df2, on="state", how="right"))

print("Outer merge:")
display(pd.merge(df1, df2, on="state", how="outer"))

Inner merge:

  state  popnsize  samplesize surveycompleted
0    UP      1000         100             Yes
1    MP      2000         200              No
2    AP      3000         300             Yes
3    JK      4000         400              No

Left merge:

  state  popnsize  samplesize surveycompleted
0    UP      1000         100             Yes
1    MP      2000         200              No
2    AP      3000         300             Yes
3    JK      4000         400              No

Right merge:

  state  popnsize  samplesize surveycompleted
0    UP      1000         100             Yes
1    MP      2000         200              No
2    AP      3000         300             Yes
3    JK      4000         400              No

Outer merge:

  state  popnsize  samplesize surveycompleted
0    AP      3000         300             Yes
1    JK      4000         400              No
2    MP      2000         200              No
3    UP      1000         100             Yes

## 21. `rbind()` equivalent

The notes use `rbind()` to append one data frame below another. fileciteturn1file0L784-L790

In [31]:
df11 = pd.DataFrame({
    "state": ["UP", "MP", "AP", "JK"],
    "popnsize": [1000, 2000, 3000, 4000]
})

df22 = pd.DataFrame({
    "state": ["Bihar", "Delhi", "Punjab"],
    "popnsize": [100, 200, 300]
})

print("df11:")
display(df11)

print("df22:")
display(df22)

df11:

  state  popnsize
0    UP      1000
1    MP      2000
2    AP      3000
3    JK      4000

df22:

    state  popnsize
0   Bihar       100
1   Delhi       200
2  Punjab       300

In [32]:
# pandas equivalent of rbind()
rbind_result = pd.concat(
    [df11, df22],
    ignore_index=True
)

rbind_result

    state  popnsize
0      UP      1000
1      MP      2000
2      AP      3000
3      JK      4000
4   Bihar       100
5   Delhi       200
6  Punjab       300

## 22. Complete practice cell

In [33]:
# Quick verification of all major operations

print("=== STRING OPERATIONS ===")
sample = "Mr. Singh met Mr. Singh."
print("sub equivalent:", re.sub("Mr\\. Singh", "Professor Jha", sample, count=1))
print("gsub equivalent:", re.sub("Mr\\. Singh", "Professor Jha", sample))
print("grep-style indices:", [i + 1 for i, s in enumerate([sample, "R Course"]) if re.search("Singh", s)])
print("grepl-style result:", [re.search("Singh", s) is not None for s in [sample, "R Course"]])

print("\n=== DATA FRAME OPERATIONS ===")
print("Painters shape:", painters.shape)
print("School frequencies:")
print(painters["School"].value_counts().sort_index())

print("\nSchool F:")
display(painters[painters["School"] == "F"])

print("\ncbind result:")
display(cbind_result)

print("\nmerge result:")
display(merge_result)

print("\nrbind result:")
display(rbind_result)

=== STRING OPERATIONS ===
sub equivalent: Professor Jha met Mr. Singh.
gsub equivalent: Professor Jha met Professor Jha.
grep-style indices: [1]
grepl-style result: [True, False]

=== DATA FRAME OPERATIONS ===

NameError: name 'painters' is not defined

# Final Summary

| R function / operation | Python equivalent used |
|---|---|
| `sub()` | `re.sub(..., count=1)` |
| `gsub()` | `re.sub()` |
| `grep()` | `re.search()` / list filtering |
| `grepl()` | Boolean `re.search()` checks |
| `data.frame()` | `pandas.DataFrame()` |
| `rownames()` | DataFrame `.index` |
| `is.numeric()` | pandas numeric dtype checks |
| `is.factor()` | pandas categorical dtype |
| `summary()` | `.describe()` / `.value_counts()` |
| `subset()` | Boolean indexing / `.loc[]` |
| `split()` | `.groupby()` |
| `cbind()` | `pd.concat(..., axis=1)` |
| `merge()` | `pd.merge()` |
| `rbind()` | `pd.concat(..., axis=0)` |

This notebook is a Python implementation of the functions and examples covered in the supplied Week 10 notes rather than an R runtime notebook.