Create Matrix

In [ ]:
x <- matrix(nrow=4, ncol=2, data=1:8, byrow=TRUE)

x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

Rename rows and columns

In [ ]:
rownames(x) <- c("r1", "r2", "r3", "r4")
colnames(x) <- c("c1", "c2")

x

   c1 c2
r1 1  2
r2 3  4
r3 5  6
r4 7  8

Create matrix with same value everywhere

In [ ]:
x <- matrix(nrow=4, ncol=2, data=2)

x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

Diagonal Matrix

In [ ]:
d <- diag(1, nrow=3, ncol=3)

d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [ ]:
d <- diag(5, nrow=3, ncol=3)

d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

Transpose of matric

In [ ]:
x <- matrix(nrow=4, ncol=2, data=1:8, byrow=TRUE)

x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
xt <- t(x)

xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [ ]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

Row sums

In [ ]:
rowSums(x)

[1]  3  7 11 15

Column sums

In [ ]:
colSums(x)

[1] 16 20

In [ ]:
rowSums(x)   # sum of each row
colSums(x)   # sum of each column

[1] 16 20

Row means

In [ ]:
rowMeans(x)

[1] 1.5 3.5 5.5 7.5

Column means

In [ ]:
colMeans(x)

[1] 4 5

Access a complete row

In [ ]:
x[3,]

[1] 5 6

Access a complete column

In [ ]:
x[,2]

[1] 2 4 6 8

Access a submatrix

In [ ]:
x[2:4, 1:2]

     [,1] [,2]
[1,] 3    4
[2,] 5    6
[3,] 7    8

Add constant to every element

In [ ]:
x + 5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

Subtract a constant

In [ ]:
x - 5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

Multiply matrix by constant

In [ ]:
5 * x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

Divide matrix by a constant

In [ ]:
x / 2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

Matrix addition

In [ ]:
x <- matrix(nrow=4, ncol=2, data=1:8, byrow=TRUE)

y <- matrix(nrow=4, ncol=2, data=11:18, byrow=TRUE)

x + y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

Matrix Substraction

In [ ]:
x - y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

Matrix multiplication

In [ ]:
x <- matrix(nrow=4, ncol=2, data=1:8, byrow=TRUE)

y <- matrix(nrow=2, ncol=4, data=11:18, byrow=TRUE)

x %*% y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

Transpose X matrix

In [27]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

Matrix x transpose

In [28]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

Cross Product

In [29]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

Concatenate matrices row wise

In [31]:
x <- matrix(nrow=3, ncol=2, data=1:6, byrow=TRUE)

y <- matrix(nrow=3, ncol=2, data=11:16, byrow=TRUE)

rbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

Concatenate matrices column wise

In [32]:
cbind(x, y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

Inverse matric

In [34]:
y <- matrix(
  nrow=2,
  ncol=2,
  byrow=TRUE,
  data=c(84,100,100,120)
)

solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

Eigen valuse

In [35]:
y <- matrix(
  nrow=2,
  ncol=2,
  byrow=TRUE,
  data=c(84,100,100,120)
)

solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05